import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavBar } from "@/components";
import Footer from "@/components/Footer";
import Image from "next/image";
import { png_logo } from "@/public/images";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mushaichi Ken",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
